### ISSUE TITLE
Unexpected symbol: To

### ISSUE THREAD

**Issue by boyds** [BlissMediaSolutions/Battleships#12]
When importing the source into Enterprise Architect for documentation purposes, the following error:
There was an error passing E:\Battleship\src\Model\SeaGrid.vb on line 15. Unexpected symbol: To

Not sure if this is only an issue with EA or the code ..needs investigation.

**Comment by BlissMediaSolutions** [comment]
It may be an error with Enterprise Architect...
the actual line in question is this:
`Private _GameTiles(0 To Width - 1, 0 To Height - 1) As Tile`

While in VB.Net variables are commonly declared with "Dim", Class level variables (which this is) is declared without the Dim statement.
If it was a bug with the code, then the declaration would be something like this:
`Private _GameTiles As Tile = 0 To Width - 1 & 0 To Height - 1`

Additionally, the use of the word "To" (which is what Enterprise Architect is flagging) is correct.  For example in a for loop you would use;
`For value As Integer = 10 To 0 Step -2`

So im thinking it wont be a bug with the code, otherwise we'd see more serious issues when running the program.

**Comment by BlissMediaSolutions** [comment]
Other possible thing to consider, not many languages make use of the word "To".
For example, in C# a for loop doesn't use it;
`for (int i = 1; i <= 5; i++)`

So maybe Enterprise Architecture is getting its different language syntax confused?

**Comment by boyds** [comment]
Ok, it's good to have you look over the syntax and confirm it's correct ..I wasn't sure.

I'm happy to close this off as an error with EA rather than being a syntax or coding error.
